### PR TITLE
Update runtime

### PR DESCRIPTION
**Pull request by bbhtt**
Is wayland not supported? It's seems to use GTK3, which supports native wayland.

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
> Build [13648 failed](https://buildbot.flathub.org/#/builders/6/builds/13648)

```
FAILED: ...
../src/photon/updates.vala:118.21-118.43: error: Invalid regular expression `//([\w\d- ]+):\s+(.+)'.
  118 |                     (/([\w\d- ]+):\s+(.+)/).match(line, 0, out match);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~                           
```

**Comment by bbhtt** [comment]
Hello @jameswestman can you please review? Thanks!

**Comment by jameswestman** [comment]
Thanks for this, and sorry about the delay. LGTM!

**Pull request merged**
